name: Notify GAA Momentum

on:
  schedule:
    - cron: "30 0 * * *"      # täglich 00:30 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  gaa:
    runs-on: ubuntu-latest

    steps:
      # ------------------------------------------------------------------
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yahooquery yfinance pandas jq

      # ------------------------------------------------------------------
      - name: Run GAA script
        run: python main_gaa.py

      # **** Debug‑Schritt: zeigt alle Dateien im Workspace ****
      - name: Show workspace tree
        run: |
          echo "=== Workspace after script run ==="
          ls -R

      # ------------------------------------------------------------------
      - name: Read content from file
        id: read_file
        run: |
          if [[ -s message.txt ]]; then
            CONTENT=$(jq -Rs . < message.txt)
            echo "CONTENT=$CONTENT" >> $GITHUB_ENV
          else
            echo "CONTENT=" >> $GITHUB_ENV
          fi

      - name: Send to Discord
        if: env.CONTENT != ''
        env:
          CONTENT: ${{ env.CONTENT }}
          DISCORD_WEBHOOK_URL: ${{ secrets.WEBHOOK_GAA }}
        run: |
          curl -s -X POST -H "Content-Type: application/json" \
               -d "{\"content\": ${CONTENT} }" \
               "$DISCORD_WEBHOOK_URL"

      # ------------------------------------------------------------------
      - name: Commit gaa_history
        run: |
          git config --global user.name  "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          # gaa_history.csv versionieren, wenn vorhanden
          if [[ -f gaa_history.csv ]]; then
            git add gaa_history.csv
            git commit -m "Update GAA history" || echo "nothing to commit"
            git push || echo "nothing to push"
          else
            echo "No gaa_history.csv found – nothing to commit."
          fi
