name: Notify GAA Momentum

on:
  # lieber nur einmal pro Tag (UTC 00:30)
  schedule:
    - cron: "30 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  gaa:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with: { python-version: "3.11" }

      - run: |
          python -m pip install --upgrade pip
          pip install yahooquery yfinance pandas jq

      - name: Run GAA script
        run: python main_gaa.py

      - name: Send to Discord
        if: success() && (steps.generate.outputs.size != '0')
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          [ -s message.txt ] || exit 0
          content=$(jq -Rs . < message.txt)
          curl -X POST -H "Content-Type: application/json" \
               -d "{\"content\": ${content} }" "$DISCORD_WEBHOOK_URL"

      - name: Commit gaa_history
        run: |
          git config --global user.name  "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          [ -e gaa_history.csv ] && git add gaa_history.csv
          git commit -m "Update GAA history" || exit 0
          git push
