name: Notify SPY‑TIPS Strategy

on:
  schedule:
    - cron: "0 12 * * *"      # Beispiel: täglich 12 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  spy_tips:
    runs-on: ubuntu-latest

    steps:
      # ---------------------------------------------------------------
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install yahooquery pandas jq

      # ---------------------------------------------------------------
      - name: Run SPY‑TIPS script
        run: python main_spy_tips.py

      - name: Read content from file
        id: read_file
        run: |
          if [[ -s message.txt ]]; then
            CONTENT=$(jq -Rs . < message.txt)   # JSON‑safe
            echo "CONTENT=$CONTENT" >> $GITHUB_ENV
          else
            echo "CONTENT=" >> $GITHUB_ENV
          fi

      - name: Send notification to Discord
        if: env.CONTENT != ''                   # <<< gültige Expression
        env:
          CONTENT: ${{ env.CONTENT }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          curl -s -X POST -H "Content-Type: application/json" \
               -d "{\"content\": ${CONTENT} }" \
               "$DISCORD_WEBHOOK_URL"
