name: Notify SPY‑TIPS Strategy

on:
  schedule:
    - cron: "0 12 * * *"      # z.B. jeden Tag 12:00 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  spy_tips:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with: { python-version: "3.11" }

      - run: |
          python -m pip install --upgrade pip
          pip install yahooquery pandas jq

      - name: Run SPY‑TIPS script
        run: python main_spy_tips.py

      - name: Send to Discord
        if: success() && [ -s message.txt ]
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          content=$(jq -Rs . < message.txt)
          curl -X POST -H "Content-Type: application/json" \
               -d "{\"content\": ${content} }" "$DISCORD_WEBHOOK_URL"
