name: ULT-GTAA Signal Bot

on:
  schedule:
    - cron: "5 20 * * *"
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  run-signal-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps (minimal)
        run: |
          python -m pip install --upgrade pip
          pip install yfinance pandas numpy requests

      - name: Run ULT-GTAA Signal Generator
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.WEBHOOK_GAA }}
        run: |
          python run_ult_gtaa.py

      - name: Commit CSV if created
        run: |
          if [ -d "signals" ] && [ "$(ls -A signals/*.csv 2>/dev/null)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add signals/*.csv
            git commit -m "Add ULT-GTAA CSV signal for $(date -u +'%Y-%m-%d')" || echo "No CSV changes to commit"
            git push
          fi

